# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5.QtCore import QRect
from PyQt5.QtWidgets import QAction, QMenuBar, QMenu, QStatusBar, QMessageBox

sys.path.append("..")

print(sys.path)

from PyQt5 import QtCore, QtGui, QtWidgets

from views.add_dialog import Ui_dialog
from controllers.controller import inwards_model, outwards_model, inventory_model


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(800, 600)
        main_window.setMinimumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../assets/icons/layers.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main_window.setWindowIcon(icon)
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.central_widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tab_widget = QtWidgets.QTabWidget(self.central_widget)
        self.tab_widget.setStatusTip("")
        self.tab_widget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_widget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_widget.setDocumentMode(False)
        self.tab_widget.setTabsClosable(False)
        self.tab_widget.setMovable(True)
        self.tab_widget.setTabBarAutoHide(False)
        self.tab_widget.setObjectName("tab_widget")
        self.inward_tab = QtWidgets.QWidget()
        self.inward_tab.setAcceptDrops(False)
        self.inward_tab.setAccessibleName("")
        self.inward_tab.setObjectName("inward_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.inward_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.group_box = QtWidgets.QGroupBox(self.inward_tab)
        self.group_box.setStatusTip("")
        self.group_box.setObjectName("group_box")
        self.gridLayout = QtWidgets.QGridLayout(self.group_box)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontal_layout = QtWidgets.QHBoxLayout()
        self.horizontal_layout.setObjectName("horizontal_layout")
        self.add_button = QtWidgets.QToolButton(self.group_box)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../assets/icons/add-ellipse.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_button.setIcon(icon1)
        self.add_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.add_button.setObjectName("add_button")
        self.add_button.clicked.connect(self.open_add_dialog)
        self.horizontal_layout.addWidget(self.add_button)
        self.delete_button = QtWidgets.QToolButton(self.group_box)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../Downloads/icons/close-ellipse.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_button.setIcon(icon2)
        self.delete_button.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.delete_button.setObjectName("edit_button")
        self.horizontal_layout.addWidget(self.delete_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontal_layout, 0, 0, 1, 1)
        self.inwards_table = QtWidgets.QTableView(self.group_box)
        self.inwards_table.setStatusTip("")
        self.inwards_table.setObjectName("table_view")
        self.inwards_table.setModel(inwards_model)
        self.gridLayout.addWidget(self.inwards_table, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.group_box)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../assets/icons/download.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tab_widget.addTab(self.inward_tab, icon3, "")
        self.outward_tab = QtWidgets.QWidget()
        self.outward_tab.setObjectName("outward_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.outward_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.group_box_2 = QtWidgets.QGroupBox(self.outward_tab)
        self.group_box_2.setStatusTip("")
        self.group_box_2.setObjectName("group_box_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.group_box_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_button_2 = QtWidgets.QToolButton(self.group_box_2)
        self.add_button_2.setIcon(icon1)
        self.add_button_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.add_button_2.setObjectName("add_button_2")
        self.horizontalLayout_2.addWidget(self.add_button_2)
        self.add_button_2.clicked.connect(self.open_add_dialog_2)
        self.delete_button_2 = QtWidgets.QToolButton(self.group_box_2)
        self.delete_button_2.setIcon(icon2)
        self.delete_button_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.delete_button_2.setObjectName("delete_button_2")
        self.horizontalLayout_2.addWidget(self.delete_button_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)

        self.gridLayout_4.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.table_view_2 = QtWidgets.QTableView(self.group_box_2)
        self.table_view_2.setStatusTip("")
        self.table_view_2.setObjectName("table_view_2")
        self.table_view_2.setModel(outwards_model)
        self.gridLayout_4.addWidget(self.table_view_2, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.group_box_2, 0, 0, 1, 1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../assets/icons/upload.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tab_widget.addTab(self.outward_tab, icon4, "")
        self.inventory_tab = QtWidgets.QWidget()
        self.inventory_tab.setObjectName("inventory_tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.inventory_tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.group_box_3 = QtWidgets.QGroupBox(self.inventory_tab)
        self.group_box_3.setStatusTip("")
        self.group_box_3.setObjectName("group_box_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.group_box_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.table_view_3 = QtWidgets.QTableView(self.group_box_3)
        self.table_view_3.setStatusTip("")
        self.table_view_3.setObjectName("table_view_3")
        self.table_view_3.setModel(inventory_model)
        self.gridLayout_6.addWidget(self.table_view_3, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.group_box_3, 0, 0, 1, 1)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../assets/icons/folder-move.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tab_widget.addTab(self.inventory_tab, icon6, "")
        self.delete_button.clicked.connect(self.deleteSelectedRow)
        self.delete_button_2.clicked.connect(self.deleteSelectedRow_2)
        self.inwards_table.verticalHeader().setVisible(False)
        self.table_view_2.verticalHeader().setVisible(False)
        self.table_view_3.verticalHeader().setVisible(False)
        self.inwards_selection_model =  self.inwards_table.selectionModel()
        self.outwards_selection_model = self.table_view_2.selectionModel()
        self.gridLayout_2.addWidget(self.tab_widget, 0, 0, 1, 1)
        main_window.setCentralWidget(self.central_widget)
        self.retranslateUi(main_window)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_window)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)


    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Bosch Inventory"))
        self.group_box.setTitle(_translate("main_window", "Manage Inwards"))
        self.add_button.setText(_translate("main_window", "Add"))
        self.delete_button.setText(_translate("main_window", "Delete"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.inward_tab), _translate("main_window", "Inword"))
        self.group_box_2.setTitle(_translate("main_window", "Manage Outwards"))
        self.add_button_2.setText(_translate("main_window", "Add"))
        self.delete_button_2.setText(_translate("main_window", "Delete"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.outward_tab), _translate("main_window", "Outward"))
        self.group_box_3.setTitle(_translate("main_window", "Manage Inventory"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.inventory_tab), _translate("main_window", "Inventory"))


    def open_add_dialog(self) -> None:
        """Add a new part to the main window"""

        dialog = QtWidgets.QDialog()
        ui = Ui_dialog()
        ui.setupUi(dialog, "Inwards")
        dialog.exec_()

    def open_add_dialog_2(self) -> None:
        """Add a new part to the main window"""

        dialog = QtWidgets.QDialog()
        ui = Ui_dialog()
        ui.setupUi(dialog, "Outwards")
        dialog.exec_()

    def deleteSelectedRow(self):
        # Get the selected indexes from the selection model
        selected_indexes = self.inwards_selection_model.selectedIndexes()

        if selected_indexes:
            for row in selected_indexes:
                # Assuming you want to delete the entire row of the first selected cell
                row = row.row()

                # Remove the row from the model
                inwards_model.removeRow(row)
                inwards_model.submitAll()  # Submit changes to the database

            # Remove the row from the model
            inwards_model.removeRow(row)
            inwards_model.submitAll()  # Submit changes to the database
            inwards_model.select()

    def deleteSelectedRow_2(self):
        # Get the selected indexes from the selection model
        selected_indexes = self.outwards_selection_model.selectedIndexes()

        if selected_indexes:
            for row in selected_indexes:
                # Assuming you want to delete the entire row of the first selected cell
                row = row.row()

                # Remove the row from the model
                outwards_model.removeRow(row)
                outwards_model.submitAll()  # Submit changes to the database

            # Remove the row from the model
            outwards_model.removeRow(row)
            outwards_model.submitAll()  # Submit changes to the database
            outwards_model.select()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())
